version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-react-app .
      - docker tag my-react-app:lategitst <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-react-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-react-app:latest
